// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.22.2
// source: api.proto

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// MetricGRPCClient is the client API for MetricGRPC service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MetricGRPCClient interface {
	Get(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type metricGRPCClient struct {
	cc grpc.ClientConnInterface
}

func NewMetricGRPCClient(cc grpc.ClientConnInterface) MetricGRPCClient {
	return &metricGRPCClient{cc}
}

func (c *metricGRPCClient) Get(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/grpc.MetricGRPC/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MetricGRPCServer is the server API for MetricGRPC service.
// All implementations must embed UnimplementedMetricGRPCServer
// for forward compatibility
type MetricGRPCServer interface {
	Get(context.Context, *Request) (*Response, error)
	mustEmbedUnimplementedMetricGRPCServer()
}

// UnimplementedMetricGRPCServer must be embedded to have forward compatible implementations.
type UnimplementedMetricGRPCServer struct {
}

func (UnimplementedMetricGRPCServer) Get(context.Context, *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedMetricGRPCServer) mustEmbedUnimplementedMetricGRPCServer() {}

// UnsafeMetricGRPCServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MetricGRPCServer will
// result in compilation errors.
type UnsafeMetricGRPCServer interface {
	mustEmbedUnimplementedMetricGRPCServer()
}

func RegisterMetricGRPCServer(s grpc.ServiceRegistrar, srv MetricGRPCServer) {
	s.RegisterService(&MetricGRPC_ServiceDesc, srv)
}

func _MetricGRPC_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetricGRPCServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.MetricGRPC/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetricGRPCServer).Get(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

// MetricGRPC_ServiceDesc is the grpc.ServiceDesc for MetricGRPC service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MetricGRPC_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.MetricGRPC",
	HandlerType: (*MetricGRPCServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _MetricGRPC_Get_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api.proto",
}
